logging:
  level:
    root: INFO
    org:
      apache:
        coyote: DEBUG
      springframework:
        web: DEBUG
        security:
          web: DEBUG
      hibernate:
        internal:
          util: DEBUG
spring:
  jpa:
    show-sql: true